config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :customers, :drycleaners
  
  resources :invoices do
    resources :items
  end

  devise_scope :user do
    authenticated :user do
      root 'invoices#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/customer.rb
class Customer < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :invoices
end

app/models/drycleaner.rb
class Drycleaner < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :customer
  belongs_to :drycleaner
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_invoice, except: [:index, :new, :create]

	def index
		if current_user.type == "Customer"
			@invoices = Invoice.where(customer_id: current_user).order("created_at DESC")
		else
			@invoices = Invoice.where(drycleaner_id: current_user).order("created_at DESC")
		end
	end

	def show
		@items = @invoice.items
	end

	def new
		@invoice = current_user.invoices.build
		@items = @invoice.items
	end

	def create
		@invoice = current_user.invoices.build(invoice_params)
		@invoice.drycleaner_email = current_user.email
		@invoice.customer_id = Customer.where(email: @invoice.customer_email).first.id
		if @invoice.save
			redirect_to invoices_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @invoice.update(invoice_params)
			redirect_to invoices_path
		else
			render 'edit'
		end
	end

	def destroy
		@invoice.destroy
		redirect_to invoices_path
	end

	private

		def invoice_params
			params.require(:invoice).permit(:name, :customer_email, :pickup)
		end

		def find_invoice
			@invoice = current_user.invoices.find(params[:id])
		end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_invoice
	before_action :find_item, only: [:edit, :update, :destroy]
	
	def new
		@item = Item.new
	end

	def create
		@item = @invoice.items.create(item_params)
		@item.invoice_id = @invoice.id

		if @item.save
			redirect_to invoice_path(@invoice)
		else
			render 'new'
		end
	end
	
	def edit
	end

	def update
		if @item.update(item_params)
			redirect_to drycleaner_invoice_path(current_user, @invoice)
		else
			render 'edit'
		end
	end

	def destroy
		@item.destroy
		redirect_to drycleaner_invoice_path(@invoice)
	end
	
	private

		def item_params
			params.require(:item).permit(:description, :quantity, :amount)
		end

		def find_invoice
			@invoice = Invoice.find(params[:invoice_id])
		end

		def find_item
			@item = @invoice.items.find(params[:id])
		end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/invoices/_invoiceform.html.erb
<% @items.each do |item| %>
  <h4><%= item.description %> <%= item.quantity %> $<%= item.amount %></h4>
<% end %>
<% if current_user.type == "Drycleaner" %>
  <% if @invoice.id %>
	  <%= link_to "Add Item", new_invoice_item_path(@invoice), class: 'btn btn-default' %>
  <% end %>
  <%= simple_form_for @invoice do |f| %>
    <div class="col-md-2 col-md-offset-5">
      <%= f.input :name %>
      <%= f.input :customer_email %>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <%= f.input :pickup %>
    </div>
    <div class="col-md-2 col-md-offset-5">
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    </div>
  <% end %>
<% else %>
  <h4>Dry Cleaner: <%= @invoice.drycleaner_email %></h4>
  <h4>Pickup Time: <%= @invoice.pickup %></h4>
<% end %>
<div id="footer">
  <h4 class="left-right">Subtotal: $<%= @invoice.subtotal %></h4>
  <h4 class="left-right" >Total: $<%= @invoice.total %></h4>
</div>

app/views/invoices/index.html.erb
<h1>Invoices</h1>
<% @invoices.each do |invoice| %>
	<div class="col-md-4 col-md-offset-4">
		<% if current_user.type == "Drycleaner" %>
			<%= link_to "Delete", invoice_path(invoice), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
		<% end %>
		<%= link_to "#{invoice.name} Pickup Time: #{invoice.pickup.strftime('%a, %d %b %Y %H:%M')}", invoice_path(invoice) %>
	</div>
<% end %>

<div class="col-md-4 col-md-offset-4">
	<% if current_user.type == "Drycleaner" %>
		<%= link_to "New Invoice", new_invoice_path, class: 'btn btn-default' %>
	<% end %>
</div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>
<%= render "invoiceform" %>

app/views/invoices/show.html.erb
<%= render "invoiceform" %>

app/views/items/new.html.erb
<div class="col-md-2 col-md-offset-5">
  <%= simple_form_for ([@invoice, @invoice.items.build]) do |f| %>
    <div class="field form-group">
      <%= f.input :description %>
      <%= f.input :quantity %>
      <%= f.input :amount %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
		<div class="container">
			<% if user_signed_in? %>
				<div class="navbar-header">
					<%= link_to "Invoices", invoices_path, class: "navbar-brand" %>
				</div>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				</ul>
			<% else %>
				<ul class="navbar-nav nav navbar-right">
					<li><%= link_to "Log In", new_user_session_path %></li>
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
				</ul>
			<% end %>
		</div>
	</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="text-center">
	<%= yield %>
</div>
</body>
</html>